@startuml
agent "Resource Notification Publisher" as Publisher
agent "Resource Notification Broker" as Broker
agent "Resource Notification Subscriber" as Subscriber
agent "Resource Notification Recipient" as Recipient
Publisher --> Broker : "Resource Publish [ITI-111]"
Subscriber --> Broker : "Resource Subscription [ITI-110]"
Subscriber --> Broker : "Resource Subscription Search [ITI-113]"
Subscriber --> Broker : "Resource SubscriptionTopic Search [ITI-118]"
Broker --> Recipient : "Resource Notify [ITI-112]"
@enduml
