@startuml
hide footbox
participant "Resource Notification Subscriber" as  Subscriber
participant "Resource Notification Broker" as  Broker


== Subscribe ==
Subscriber -> Broker : Create Subscription Request 
activate Broker
/'
participant "Resource Notification Recipient" as  Recipient
opt handskake HTTPS   
  Broker -> Recipient: Handshake Notification
  alt Handshake Success
  Recipient -> Broker: 200 OK 
  else Handshake Failure
  Recipient ->Broker: 404 Not Found
  end
end
'/
Broker --> Subscriber : Create Subscription Response Message 
deactivate Broker

== Unsubscribe ==
Subscriber -> Broker: Update Subscription Request 

activate Broker
Broker --> Subscriber: Update Subscription Response Message 
deactivate Broker

@enduml
