@startuml
hide footbox

participant "Resource Notification Broker" as  Broker
participant "Resource Notification Recipient" as  Recipient

== Handshake Notification ==
Broker -> Recipient :  Handshake Notification Message [ITI-112]
activate Recipient
Recipient --> Broker :  Handshake Notification Response [ITI-112]
deactivate Recipient

== Heartbeat Notification ==
Broker -> Recipient :  Heartbeat Notification Message [ITI-112]
activate Recipient
Recipient --> Broker :  Heartbeat Notification Response [ITI-112]
deactivate Recipient

== Event Notification ==
Broker -> Recipient :  Event Notification Message [ITI-112]activate Recipient
Recipient --> Broker :  Event Notification Response [ITI-112]
deactivate Recipient

== Subscription Deactivation Notification ==
Broker -> Recipient :  Subscription Deactivation Notification Message [ITI-112]
activate Recipient
Recipient --> Broker :  Subscription Deactivation Notification Response [ITI-112]
deactivate Recipient

@enduml