@startuml
hide footbox

participant "Resource Notification Publisher" as  Publisher
participant "Resource Notification Broker" as  Broker


activate Broker
Publisher -> Broker : 1.Resource Publish Request [ITI-111]
Broker --> Publisher : 2. Resource Publish Response [ITI-111]
deactivate Broker

@enduml