@startuml
hide footbox
participant "Resource Notification Subscriber" as  Subscriber
participant "Resource Notification Broker" as  Broker
activate Subscriber
Subscriber -> Broker : Create Subscription Request [ITI-110]
activate Broker
/'
participant "Resource Notification Recipient" as  Recipient
opt handskake HTTPS   
  Broker -> Recipient: Handshake Notification
  alt Handshake Success
  Recipient -> Broker: 200 OK 
  else Handshake Failure
  Recipient ->Broker: 404 Not Found
  end
end
'/
Broker --> Subscriber :Create Subscription Response [ITI-110]
deactivate Broker
deactivate Subscriber


Subscriber -> Broker: Update Subscription Request [ITI-110]
activate Subscriber
activate Broker
Broker --> Subscriber: Update Subscription Response [ITI-110]
deactivate Broker
deactivate Subscriber

@enduml
