@startuml
hide footbox
participant "Resource Notification Subscriber" as  Subscriber
participant "Resource Notification Broker" as  Broker



Subscriber -> Broker : 1. Resource Subscription Search Request [ITI-113]
activate Broker
Broker --> Subscriber : 2. Resource Subscription Search Response [ITI-113]

deactivate Broker

@enduml
