@startuml
hide footbox

participant "Resource Notification Publisher" as  Publisher
participant "Resource Notification Broker" as  Broker



Publisher -> Broker : Resource Publish Request [ITI-111]
activate Broker
Broker --> Publisher : Resource Publish Response [ITI-111]
deactivate Broker

@enduml