@startuml
skinparam svgDimensionStyle false
skinparam componentStyle rectangle

hide footbox
/' title "DSUBm grouped with MHD" '/


card "XDS Document Repository" as XDS_Repo 
card "Document Administrator" as DOC_Administrator
card  Registry [
  <b> Document Registry
  ----
  XDS Document Registry 
  ....
  Resource Notification  Publisher
]
card "Resource Notification Broker" as DSUBm_Broker
card "Resource Notification Subscriber" as DSUBm_Subscriber


card  Consumer_XDS[
  <b>XDS Document Consumer System
  ----
  XDS Document Consumer
  ....
  Resource Notification  Recipient
]

card  Consumer_MHD[
  <b>MHD Document Consumer System
  ----
  MHD Document Consumer
  ....
  Resource Notification  Recipient
]


DOC_Administrator --> Registry: ITI-57
DOC_Administrator --> Registry: ITI-62

XDS_Repo -d-> Registry: ITI-42
Registry -d-> DSUBm_Broker: ITI-111
DSUBm_Subscriber -l-> DSUBm_Broker: ITI-110
DSUBm_Broker --> Consumer_MHD: ITI-112
DSUBm_Broker --> Consumer_XDS: ITI-112
/'
card  ConsumerInterface [
  <b> MHD to XDS Consumer Interface
  ----
  MHD Document Recipient
  ....
  XDS Document Consumer 
]
Consumer -u-> ConsumerInterface: ITI-68
ConsumerInterface -l-> XDS_Repo: ITI-43
ConsumerInterface --> Registry: ITI-18
'/

@enduml