@startuml
skinparam svgDimensionStyle false
skinparam componentStyle rectangle

hide footbox
/' title "DSUBm grouped with DSUB: Notification Manager" '/

card "XDS Document Source" as Source
card "XDS Document Repository" as Repo

card  Central [
  <b>Central Infrastructure
  ----
  XDS Docment Registry
  ....
  DSUB Document Metadata Publisher
]

card Broker [
  <b>Notification Manager
  ----
  DSUB Document Metadata Notification Broker
  ....
  DSUBm Resource Notification Broker
]

card Subscriber [
  <b>Subscriber
  ----
  DSUB Document Metadata Subscriber
  ....
  DSUBm Resource Notification Subscriber
]

card "DSUB Document Metadata Notification Recipient" as DSUB_Recipient 



Subscriber -l-> Broker: ITI-113
Subscriber -l-> Broker: ITI-52


Source -u-> Repo: ITI-41
Repo -r-> Central: ITI-42
Central -d-> Broker: ITI-54
Broker-d-> DSUB_Recipient: ITI-53
@enduml