@startuml
skinparam svgDimensionStyle false
skinparam componentStyle rectangle

hide footbox
/' title "DSUBm grouped with DSUB: DSUB on FHIR" '/

card "XDS Document Source" as Source
card "XDS Document Repository" as Repo

card  Central [
  <b>Central Infrastructure
  ----
  XDS Document Registry
  ....
  DSUB Document Metadata Publisher
]

card "DSUB Document Metadata Notification Broker" as Broker 

card  DSUBFHIR [
  <b>DSUB/FHIR interface
  ----
DSUB Document Metadata Subscriber
....
DSUB Document Metadata Notification Recipient
....
DSUBm Resource Notification Broker
]

card "DSUBm Resource Notification Subscriber" as Subsciber 
card "DSUBm Resource Notification Recipient" as Recipient 

Subsciber -u-> DSUBFHIR: ITI-110
DSUBFHIR -d-> Broker: ITI-52

Source -u-> Repo: ITI-41
Repo -r-> Central: ITI-42
Central -d-> Broker: ITI-54

Broker-r->DSUBFHIR: ITI-53
DSUBFHIR -d-> Recipient: ITI-112



@enduml