@startuml
skinparam svgDimensionStyle false
skinparam componentStyle rectangle

hide footbox
/' title "DSUBm grouped with MHDS  grouping 2 " '/


card "DSUBm Resource Notification Recipient" as DSUBm_Recipient


card  Registry [
  <b>MHDs Document Registry
  ----
  MHD Document Responder
  ....
  MHD Document Recipient
  ....
  DSUBm Resource Notification Broker
]

card Publisher [
  <b>Document Publisher System
  ----
  MHD Document Source
]

card  Consumer [
  <b>Document Consumer System
  ----
  MHD Document Consumer
  ....
  DSUBm Resource Notification Subscriber
]


Publisher -r-> Registry: ITI-65
Consumer -l-> Registry: ITI-110
Registry -d->DSUBm_Recipient: ITI-112

@enduml