@startuml
skinparam svgDimensionStyle false
skinparam componentStyle rectangle



hide footbox
/' title "DSUBm grouped with MHD grouping 1" '/


card "XDS Document Repository" as XDS_Repo 
card "Document Administrator" as DOC_Administrator
card  Registry [
  <b> Document Registry
  ----
  XDS Document Registry 
  ....
  DSUBm Resource Notification  Publisher
]
card "DSUBm Resource Notification Broker" as DSUBm_Broker
card "DSUBm Resource Notification Subscriber" as DSUBm_Subscriber


card  Consumer_XDS[
  <b>XDS Document Consumer System
  ----
  XDS Document Consumer
  ....
  DSUBm Resource Notification Recipient
]

card  Consumer_MHD[
  <b>MHD Document Consumer System
  ----
  MHD Document Consumer
  ....
  DSUBm Resource Notification Recipient
  ....
  DSUBm Resource Notification Subscriber
]


DOC_Administrator --> Registry: ITI-57
DOC_Administrator --> Registry: ITI-62

XDS_Repo -d-> Registry: ITI-42
Registry -d-> DSUBm_Broker: ITI-111
Consumer_MHD -l-> DSUBm_Broker: ITI-110
DSUBm_Subscriber -r-> DSUBm_Broker: ITI-110
DSUBm_Broker -r-> Consumer_MHD: ITI-112
DSUBm_Broker --> Consumer_XDS: ITI-112
/'
card  ConsumerInterface [
  <b> MHD to XDS Consumer Interface
  ----
  MHD Document Recipient
  ....
  XDS Document Consumer 
]
Consumer -u-> ConsumerInterface: ITI-68
ConsumerInterface --> XDS_Repo: ITI-43
ConsumerInterface --> Registry: ITI-18
'/

@enduml