@startuml
skinparam svgDimensionStyle false
hide footbox

/'title "Subscription with DSUBm on MHDs infrastructure: Laboratory Results and ePrescription"'/
participant HospitalEHR [
    =Hospital EHR
    ----
    [MHD Document Source]
    [DSUBm Resource Notification Subscriber]
    [DSUBm Resource Notification Recipient]
    [MHD Document Consumer]
] 

participant MHDsDocumentRegistry [
    =Central Infrastructure
    ----
    [MHDs Document Registry]
    [DSUBm Resource Notification Broker]
    ] 


participant LaboratorySystem [
    =Laboratory System
    ----
    [MHD Document Source]
] 

participant NurseTablet [
    =Nurse Tablet
    ----
    [DSUBm Resource Notification Subscriber]
    [DSUBm Resource Notification Recipient]
    [MHD Document Consumer]
] 
autonumber "<b>"
NurseTablet -> MHDsDocumentRegistry:   Resource Subscription [ITI-110]
activate MHDsDocumentRegistry
deactivate MHDsDocumentRegistry
autonumber stop
HospitalEHR --> LaboratorySystem:  Laboratory Order Request
autonumber 2 "<b>"
HospitalEHR -> MHDsDocumentRegistry:  Resource Subscription [ITI-110]
activate MHDsDocumentRegistry
deactivate MHDsDocumentRegistry




LaboratorySystem -> MHDsDocumentRegistry: Provide Document Bundle [ITI-65]
activate MHDsDocumentRegistry

MHDsDocumentRegistry -> HospitalEHR : Resource Notify [ITI-112]
activate HospitalEHR
HospitalEHR -> MHDsDocumentRegistry:  Retrieve Document [ITI-68]
deactivate MHDsDocumentRegistry
HospitalEHR -> MHDsDocumentRegistry: Provide Document Bundle [ITI-65]
deactivate HospitalEHR

activate MHDsDocumentRegistry
MHDsDocumentRegistry -> NurseTablet : Resource Notify [ITI-112]
deactivate MHDsDocumentRegistry
activate NurseTablet
NurseTablet -> MHDsDocumentRegistry: Retrieve Document [ITI-68]
activate MHDsDocumentRegistry
deactivate MHDsDocumentRegistry
autonumber stop
NurseTablet -> NurseTablet: proceed with drug administration
deactivate NurseTablet

autonumber 9 "<b>"
group Unsubscribe
  HospitalEHR ->MHDsDocumentRegistry: Resource Subscription [ITI-110]
  activate MHDsDocumentRegistry
  deactivate MHDsDocumentRegistry
  
end

@enduml