@startuml
skinparam svgDimensionStyle false
hide footbox


participant HospitalEHR [
    =Hospital EHR
    ----
    [Document Source]
    [Mobile Notification Subscriber]
    [Mobile Notification Recipient]
    
] 

participant MHDsDocumentRegistry [
    =Central Infrastructure
    ----
    [MHDs Document Registry]
    [Mobile Notification Publisher]
    [Mobile Notification Broker]
    ] 



participant LaboratorySystem [
    =Laboratory System
    ----
    [Document Source]
] 

participant NurseTablet [
    =Nurse Tablet
    ----
    [Mobile Notification Subscriber]
    [Mobile Notification Recipient]
    
] 

HospitalEHR --> NurseTablet:  Clinical information exchange
NurseTablet -> MHDsDocumentRegistry:   Mobile Subscription [ITI-Y1]
activate MHDsDocumentRegistry
deactivate MHDsDocumentRegistry
HospitalEHR --> LaboratorySystem:  Laboratory Order Request

HospitalEHR -> MHDsDocumentRegistry:  Mobile Subscription [ITI-Y1]
activate MHDsDocumentRegistry
deactivate MHDsDocumentRegistry




LaboratorySystem -> MHDsDocumentRegistry: Provide Document Bundle [ITI-65]
activate MHDsDocumentRegistry
MHDsDocumentRegistry -> MHDsDocumentRegistry : Mobile Publishing [ITI-Y2]
MHDsDocumentRegistry -> HospitalEHR : Mobile Notify [ITI-Y3]
activate HospitalEHR
deactivate MHDsDocumentRegistry
deactivate HospitalEHR



HospitalEHR -> MHDsDocumentRegistry: Provide Document Bundle [ITI-65]
activate MHDsDocumentRegistry
MHDsDocumentRegistry -> MHDsDocumentRegistry : Mobile Publishing [ITI-Y2]
MHDsDocumentRegistry -> NurseTablet : Mobile Notify [ITI-Y3]
activate NurseTablet
NurseTablet -> NurseTablet: procede with drug administration
deactivate NurseTablet
deactivate MHDsDocumentRegistry

group Unsubscribe
  HospitalEHR ->MHDsDocumentRegistry: Mobile Subscription [ITI-Y1]
  activate MHDsDocumentRegistry
  deactivate MHDsDocumentRegistry
  
  NurseTablet ->MHDsDocumentRegistry: Mobile Subscription Search [ITI-Y4]
  activate MHDsDocumentRegistry
  deactivate MHDsDocumentRegistry
  
  NurseTablet ->MHDsDocumentRegistry : Mobile Subscription [ITI-Y1]
  activate MHDsDocumentRegistry
  deactivate MHDsDocumentRegistry
end

@enduml