@startuml
skinparam svgDimensionStyle false
hide footbox
/'title "Subscription with DSUBm on DSUB on FHIR infrastructure from Mobile Device" '/
participant Repository [
    =Integrated Document Source Repository
    ----
    [XDS Document Source]
    [XDS Document Repository]  
] 

participant Central [
    =Central Infrastructure
    ----
    [XDS Document Registry]
    [Document Metadata Publisher]
    [Document Metadata Broker]
    [XDS Document Consumer]
    [MHD Document Responder]
] 

participant DSUBonFHIR [
    =DSUB/FHIR Interface
    ----
    [Document Metadata Subscriber]
    [Document Metadata Notification Recipient]
    [Resource Notification Broker]
    ] 

participant MobDevice [
    =Mobile Device
    ----
    [Resource Notification Subscriber]
    [Resource Notification Recipient]
    [MHD Document Consumer]
] 

autonumber 1 "<b>"
MobDevice -> DSUBonFHIR: Resource Subscription [ITI-110]
activate DSUBonFHIR
DSUBonFHIR -> Central: Document Metadata Subscribe [ITI-52]
activate Central
deactivate Central
deactivate DSUBonFHIR

Repository -> Central: Register Document Set-b [ITI-42]
activate Central
Central -> Central:  Document Metadata Publish [ITI-54]
Central -> DSUBonFHIR: Document Metadata Notify [ITI-53]
deactivate Central

activate DSUBonFHIR
DSUBonFHIR -> MobDevice: Resource Notify [ITI-112]
deactivate DSUBonFHIR
activate MobDevice
MobDevice -> Central: Retrieve Document [ITI-68]
activate Central
Central -> Repository: Retrieve Document Set [ITI-43]
activate Repository
deactivate Repository
deactivate Central
MobDevice -> MobDevice: review the appointment data
deactivate MobDevice


@enduml