@startuml
skinparam svgDimensionStyle false
hide footbox
/'title "Folder Subscription with DSUBm on MHDs infrastructure" '/

participant DHR [
    = Diabetological Healthcare Record
    ----
    [MHD Document Consumer]
    [Resource Notification Subscriber]
    [Resource Notification Recipient]
] 



participant Central [
    =Electronic Healthcare Record
    ----
    [MHDs Document Registry]
    [Resource Notification Publisher]
    [Resource Notification Broker]
] 

participant ER [
    =Emergency Room
    ----
    [MHD Document Source]
] 




DHR -> DHR: First visit (therapy A)
autonumber "<b>"
activate DHR
DHR -> Central:  Resource Subscription [ITI-110]
deactivate DHR
ER->Central:  Provide Document Bundle [ITI-65]
activate Central 
Central -> Central: Resource Publish [ITI-111]
Central -> DHR: Resource Notify [ITI-112]
deactivate Central
activate DHR
DHR -> ER: Retrieve Document [ITI-68]
activate ER
deactivate ER
deactivate DHR 

DHR -> DHR: Second visit (therapy B)
ER->Central:  Provide Document Bundle [ITI-65]
activate Central 
Central -> Central: Resource Publish [ITI-111]
Central -> DHR: Resource Notify [ITI-112]
deactivate Central
activate DHR

DHR -> ER: Retrieve Document [ITI-68]
activate ER
deactivate ER
deactivate DHR 
autonumber stop 
DHR -> DHR: Third visit. (Unsubscribe)
activate DHR
autonumber 11 "<b>"
DHR -> Central: Resource Subscription Search [ITI-113]
DHR -> Central: Resource Subscription [ITI-110]	
deactivate DHR

@enduml