@startuml
skinparam svgDimensionStyle false
hide footbox

title "Subscription with DSUBm on MHDs infrastructure: Laboratory Results and ePrescription"
participant HospitalEHR [
    =Hospital EHR
    ----
    [Document Source]
    [Mobile Notification Subscriber]
    [Mobile Notification Recipient]
    
] 

participant MHDsDocumentRegistry [
    =Central Infrastructure
    ----
    [MHDs Document Registry]
    [Mobile Notification Publisher]
    [Mobile Notification Broker]
    ] 


participant LaboratorySystem [
    =Laboratory System
    ----
    [Document Source]
] 

participant NurseTablet [
    =Nurse Tablet
    ----
    [Mobile Notification Subscriber]
    [Mobile Notification Recipient]
    
] 

NurseTablet -> MHDsDocumentRegistry:   Mobile Subscription [ITI-Y1]
activate MHDsDocumentRegistry
deactivate MHDsDocumentRegistry
HospitalEHR --> LaboratorySystem:  Laboratory Order Request

HospitalEHR -> MHDsDocumentRegistry:  Mobile Subscription [ITI-Y1]
activate MHDsDocumentRegistry
deactivate MHDsDocumentRegistry




LaboratorySystem -> MHDsDocumentRegistry: Provide Document Bundle [ITI-65]
activate MHDsDocumentRegistry
MHDsDocumentRegistry -> MHDsDocumentRegistry : Mobile Publishing [ITI-Y2]
MHDsDocumentRegistry -> HospitalEHR : Mobile Notify [ITI-Y3]
activate HospitalEHR

HospitalEHR -> MHDsDocumentRegistry:  Retrieve Document [ITI-68]
deactivate MHDsDocumentRegistry
HospitalEHR -> MHDsDocumentRegistry: Provide Document Bundle [ITI-65]
deactivate HospitalEHR

activate MHDsDocumentRegistry
MHDsDocumentRegistry -> MHDsDocumentRegistry : Mobile Publishing [ITI-Y2]
MHDsDocumentRegistry -> NurseTablet : Mobile Notify [ITI-Y3]
deactivate MHDsDocumentRegistry
activate NurseTablet
NurseTablet -> MHDsDocumentRegistry: Retrieve Document [ITI-68]
activate MHDsDocumentRegistry
deactivate MHDsDocumentRegistry
NurseTablet -> NurseTablet: procede with drug administration
deactivate NurseTablet


group Unsubscribe
  HospitalEHR ->MHDsDocumentRegistry: Mobile Subscription [ITI-Y1]
  activate MHDsDocumentRegistry
  deactivate MHDsDocumentRegistry
  
end

@enduml