@startuml
skinparam svgDimensionStyle false
hide footbox
/'title "Subscription with DSUBm on MHD on FHIR infrastructure from Mobile Device" '/

participant Repository [
    =Integrated Document Source Repository
    ----
    [XDS Document Source]
    [XDS Document Repository]  
] 

participant Central [
    =Central Infrastructure
    ----
    [XDS Document Registry]
    [DSUBm Resource Notification Publisher]
] 

participant Broker [
    =Notification Broker
    ----
    [DSUBm Resource Notification Broker]
] 

participant XDSonFHIR [
    =XDS FHIR Interface
    ----
    [XDS Document Consumer]
    [MHD Document Responder]
] 

participant MobileDevice [
    =Mobile Device
    ----
    [MHD Document Consumer]
    [DSUBm Resource Notification Subscriber]
    [DSUBm Resource Notification Recipient]
] 
autonumber 1 "<b>"
MobileDevice -> Central: Resource Subscription [ITI-110]
activate Central
deactivate Central

Repository -> Central: Register Document Set-b [ITI-42]
activate Central
Central -> Broker :  Resource Publish [ITI-111]
deactivate Central
activate Broker
Broker -> MobileDevice: Resource Notify [ITI-112]
deactivate Broker

activate MobileDevice
MobileDevice -> XDSonFHIR: Retrieve Document [ITI-68]
activate XDSonFHIR
XDSonFHIR -> Repository: Retrieve Document Set [ITI-43]
activate Repository
deactivate XDSonFHIR
deactivate Repository
MobileDevice -> MobileDevice: prepare the ePrescription\nto be used in the local pharmacy
deactivate MobileDevice


@enduml