@startuml
skinparam svgDimensionStyle false
hide footbox
/'title "Folder Subscription with DSUBm on MHDs infrastructure" '/

participant DHR [
    = Diabetological Healthcare Record
    ----
    [MHD Document Consumer]
    [Mobile Notification Subscriber]
    [Mobile Notification Recipient]
] 



participant Central [
    =Electronic Healthcare Record
    ----
    [MHDs Document Registry]
    [Mobile Notification Publisher]
    [Mobile Notification Broker]
] 

participant ER [
    =Emergency Room
    ----
    [MHD Document Source]
] 




DHR -> DHR: Firt visit (therapy A)
activate DHR
DHR -> Central:  Mobile Subscription [ITI-Y1]
deactivate DHR

ER->Central:  Provide Document Bundle [ITI-65]
activate Central 
Central -> Central: Mobile Publish [ITI-Y2]
Central -> DHR: Mobile Notify [ITI-Y3]
deactivate Central
activate DHR

DHR -> ER: Retrieve Document [ITI-68]
activate ER
deactivate ER
deactivate DHR 

DHR -> DHR: Second visit (therapy B)

ER->Central:  Provide Document Bundle [ITI-65]
activate Central 
Central -> Central: Mobile Publish [ITI-Y2]
Central -> DHR: Mobile Notify [ITI-Y3]
deactivate Central
activate DHR

DHR -> ER: Retrieve Document [ITI-68]
activate ER
deactivate ER
deactivate DHR 

DHR -> DHR: Third visit. (Unsubscribe)
activate DHR
DHR -> Central: Mobile Subscription Search [ITI-Y4]
DHR -> Central: Mobile Subscription [ITI-Y1]	
deactivate DHR

@enduml