@startuml
skinparam svgDimensionStyle false
hide footbox

/'title "Subscription with DSUBm on MHDs infrastructure with pull notification" '/
participant HospitalEHR [
    = Hospital EHR
    ----
    [MHD Document Source]
] 

participant MHDsDocumentRegistry [
    =Central Infrastructure
    ----
    [MHDs Document Registry]
    [Resource Notification Publisher]
] 

participant Broker[
    = Broker
    ----
    [Resource Notification Broker]
    [Resource Notification Recipient]
]

participant App [
    = Visit App
    ----
    [Resource Notification Subscriber]
    [MHD Document Consumer]
] 

autonumber "<b>"
group First Visit
  App -> Broker:   Resource Subscription [ITI-110]
  activate Broker
  deactivate Broker
end
HospitalEHR -> MHDsDocumentRegistry:  Provide Document Bundle [ITI-65]
MHDsDocumentRegistry -> Broker : Resource Publish [ITI-111]
activate Broker
Broker -> Broker : Resource Notify [ITI-112]
deactivate Broker


group Second Visit
  App -> Broker: Resource Subscription Search [ITI-113] ($events operation)
  activate BRoker
  deactivate MHDsDocumentRegistry
  App -> MHDsDocumentRegistry: Retrieve Document [ITI-68]
  activate MHDsDocumentRegistry
  deactivate MHDsDocumentRegistry
end


@enduml