# sushi-config.yaml is documented https://fshschool.org/docs/sushi/configuration/
# ───────────────────────────────────────────────────
# the id should be lowercase made up of "ihe." + {domain acronym} + "." + {profile acronym/short-name}
# e.g. ihe.iti.mhds, or ihe.iti.basicaudit
id: ihe.iti.dsubm
canonical: https://profiles.ihe.net/ITI/DSUBm
version: 1.0.1-current
name: IHE_ITI_DSUBm
title: "Document Subscription for Mobile (DSUBm)"
description:  profile describes the use of document subscription and notification mechanisms for RESTful applications. 
releaseLabel: ci-build
#releaseLabel: Trial-Implementation
#releaseLabel: ballot
#date: 2023-11-17
status: active
publisher:
  ## Find your domain contact on the https://www.ihe.net/ihe_domains page
  - name: IHE IT Infrastructure Technical Committee
  - url: https://www.ihe.net/ihe_domains/it_infrastructure/
  - email: iti@ihe.net
contact:
  - name: IHE IT Infrastructure Technical Committee
    telecom:
      - system: email
        value: iti@ihe.net
license:  CC-BY-4.0
fhirVersion: 4.3.0
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
#copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2023+

dependencies: 
  hl7.fhir.uv.subscriptions-backport.r4b: 
    version: 1.1.x
    uri: http://hl7.org/fhir/uv/subscriptions-backport/ImplementationGuide/hl7.fhir.uv.subscriptions-backport 
  ihe.iti.mhd: 
    version: 4.2.x
    uri: https://profiles.ihe.net/ITI/MHD/ImplementationGuide/ihe.iti.mhd
#  hl7.terminology.r4: 5.3.0
#  hl7.fhir.uv.extensions: current



parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'


# list every examplehere with a name, description and that exampleBoolean is true; These are used to populate the artifacts page, and are needed to eliminate build warnings 
# You may delay filling out this section until you approach publication as it is merely a nice to have and eliminates build warnings -- If you do this then you will need above the autoload-resources true
#resources:
# Subscription/Subscription:
#  Patient/my-example-patient:
#    name: My Example Patient
#    description: An example Patient
#    exampleBoolean: true
#  Patient/bad-example: omit


    
#  Subscription/DSUBm-Subscription:
#    name: my example Subscription
#    description: aAn example of Subscription



pages:
# itemize here each narrative page. Include assigned section numbers when appropriate. The order they appear here is the order they will appear in the TOC and on the next/prev navigation.
  index.md:
    title: Document Subscription for Mobile (DSUBm) Home
    generation: markdown
  volume-1.md:
    title: 1:54 Document Subscription for Mobile (DSUBm)
    generation: markdown
  ITI-110.md:
    title: 2:3.110 Resource Subscription [ITI-110]
    generation: markdown
  ITI-111.md:
    title: 2:3.111 Resource Publish [ITI-111]
    generation: markdown
  ITI-112.md:
    title: 2:3.112 Resource Notify [ITI-112]
    generation: markdown
  ITI-113.md:
    title: 2:3.113 Resource Subscription Search [ITI-113]
    generation: markdown
  ITI-114.md:
    title: 2:3.114 Resource SubscriptionTopic Search [ITI-114]
    generation: markdown
  testplan.md:
    title: "Test Plan"
    generation: markdown
  other.md:
    title: Changes to Other IHE Specifications
    generation: markdown
  download.md:
    title: "Download and Analysis"
    generation: markdown
  issues.md:
    title: Significant Changes and Issues
    generation: markdown

menu:
  DSUBm Home: index.html
  Volume 1:
#    Introduction: volume-1.html
    Actors and Transactions: volume-1.html#1541-dsubm-actors-transactions-and-content-modules
    Actor Options: volume-1.html#1542-actor-options
    Required Groupings: volume-1.html#1543-required-actor-groupings
    Overview: volume-1.html#1544-dsubm-overview
    Security Considerations: volume-1.html#1545-security-considerations
    Cross-Profile Considerations: volume-1.html#1546-cross-profile-considerations
  Volume 2:
    "Resource Subscription [ITI-110]": ITI-110.html
    "Resource Publish [ITI-111]": ITI-111.html
    "Resource Notify [ITI-112]": ITI-112.html
    "Resource Subscription Search [ITI-113]": ITI-113.html
    "Resource SubscriptionTopic Search [ITI-114]": ITI-114.html
  Artifacts: artifacts.html
  Other:
    Changes to Other IHE Specifications: other.html
    Download and Analysis: download.html
    Test Plan: testplan.html